employees=[{"eid":1,"ename":"Rubi","gender":"Female","country":"Philippines"},
{"eid":2,"ename":"Corty","gender":"Male","country":"Nigeria"},
{"eid":3,"ename":"Hersh","gender":"Male","country":"Brazil"},
{"eid":4,"ename":"Kira","gender":"Genderqueer","country":"Indonesia"},
{"eid":5,"ename":"Ingar","gender":"Male","country":"Bangladesh"},
{"eid":6,"ename":"Helaine","gender":"Female","country":"Russia"},
{"eid":7,"ename":"Francklyn","gender":"Male","country":"China"},
{"eid":8,"ename":"Morly","gender":"Male","country":"Portugal"},
{"eid":9,"ename":"Andie","gender":"Genderqueer","country":"Slovenia"},
{"eid":10,"ename":"Anna-maria","gender":"Female","country":"China"},
{"eid":11,"ename":"Dulcie","gender":"Genderfluid","country":"Morocco"},
{"eid":12,"ename":"Clemence","gender":"Female","country":"Georgia"},
{"eid":13,"ename":"Garwood","gender":"Male","country":"Haiti"},
{"eid":14,"ename":"Hollyanne","gender":"Agender","country":"Indonesia"},
{"eid":15,"ename":"Hallie","gender":"Female","country":"Finland"},
{"eid":16,"ename":"Darbee","gender":"Male","country":"Azerbaijan"},
{"eid":17,"ename":"Margi","gender":"Female","country":"Poland"},
{"eid":18,"ename":"Odele","gender":"Female","country":"Czech Republic"},
{"eid":19,"ename":"Marigold","gender":"Female","country":"France"},
{"eid":20,"ename":"Phoebe","gender":"Female","country":"Morocco"},
{"eid":21,"ename":"Graehme","gender":"Male","country":"Norway"},
{"eid":22,"ename":"Randie","gender":"Male","country":"Afghanistan"},
{"eid":23,"ename":"Frazer","gender":"Male","country":"Russia"},
{"eid":24,"ename":"Dolli","gender":"Female","country":"Argentina"},
{"eid":25,"ename":"Lester","gender":"Male","country":"China"},
{"eid":26,"ename":"Theadora","gender":"Female","country":"Germany"},
{"eid":27,"ename":"Bettine","gender":"Female","country":"China"},
{"eid":28,"ename":"Aili","gender":"Female","country":"Portugal"},
{"eid":29,"ename":"Osbourne","gender":"Male","country":"China"},
{"eid":30,"ename":"Glendon","gender":"Male","country":"China"},
{"eid":31,"ename":"Ben","gender":"Male","country":"Indonesia"},
{"eid":32,"ename":"Henri","gender":"Male","country":"Bolivia"},
{"eid":33,"ename":"Noel","gender":"Male","country":"Norway"},
{"eid":34,"ename":"Jolie","gender":"Genderfluid","country":"Indonesia"},
{"eid":35,"ename":"Peter","gender":"Male","country":"Russia"},
{"eid":36,"ename":"Nessie","gender":"Female","country":"China"},
{"eid":37,"ename":"Eydie","gender":"Female","country":"Peru"},
{"eid":38,"ename":"Corinne","gender":"Female","country":"Russia"},
{"eid":39,"ename":"Markus","gender":"Male","country":"United States"},
{"eid":40,"ename":"Olenka","gender":"Polygender","country":"France"},
{"eid":41,"ename":"Jaquelyn","gender":"Agender","country":"China"},
{"eid":42,"ename":"Krishna","gender":"Male","country":"Micronesia"},
{"eid":43,"ename":"Huberto","gender":"Male","country":"Brazil"},
{"eid":44,"ename":"Davina","gender":"Female","country":"Indonesia"},
{"eid":45,"ename":"Gordon","gender":"Male","country":"Philippines"},
{"eid":46,"ename":"Walden","gender":"Male","country":"Venezuela"},
{"eid":47,"ename":"Gerty","gender":"Female","country":"Russia"},
{"eid":48,"ename":"Alayne","gender":"Female","country":"United States"},
{"eid":49,"ename":"Aleksandr","gender":"Male","country":"China"},
{"eid":50,"ename":"Francisco","gender":"Male","country":"Belarus"},
{"eid":51,"ename":"Opal","gender":"Female","country":"Japan"},
{"eid":52,"ename":"Gerianne","gender":"Female","country":"Azerbaijan"},
{"eid":53,"ename":"Duffie","gender":"Male","country":"Kyrgyzstan"},
{"eid":54,"ename":"Robbi","gender":"Female","country":"Pakistan"},
{"eid":55,"ename":"Cary","gender":"Genderfluid","country":"Cameroon"},
{"eid":56,"ename":"Zoe","gender":"Female","country":"Russia"},
{"eid":57,"ename":"Zonda","gender":"Female","country":"Brazil"},
{"eid":58,"ename":"Clio","gender":"Female","country":"Venezuela"},
{"eid":59,"ename":"Aurora","gender":"Female","country":"Guatemala"},
{"eid":60,"ename":"Jermaine","gender":"Male","country":"Russia"},
{"eid":61,"ename":"Mylo","gender":"Genderfluid","country":"Poland"},
{"eid":62,"ename":"Lew","gender":"Male","country":"Brazil"},
{"eid":63,"ename":"Gabbey","gender":"Female","country":"Palestinian Territory"},
{"eid":64,"ename":"Clea","gender":"Genderqueer","country":"Sweden"},
{"eid":65,"ename":"Jorgan","gender":"Male","country":"Spain"},
{"eid":66,"ename":"Sena","gender":"Female","country":"Indonesia"},
{"eid":67,"ename":"Yancy","gender":"Male","country":"China"},
{"eid":68,"ename":"Lockwood","gender":"Male","country":"China"},
{"eid":69,"ename":"Pearla","gender":"Female","country":"Greece"},
{"eid":70,"ename":"Annabel","gender":"Female","country":"Montenegro"},
{"eid":71,"ename":"Emlyn","gender":"Female","country":"Brazil"},
{"eid":72,"ename":"Stanislaw","gender":"Male","country":"China"},
{"eid":73,"ename":"Timmi","gender":"Female","country":"Norfolk Island"},
{"eid":74,"ename":"Hatty","gender":"Female","country":"Peru"},
{"eid":75,"ename":"Gustie","gender":"Female","country":"China"},
{"eid":76,"ename":"Scot","gender":"Male","country":"Sweden"},
{"eid":77,"ename":"Balduin","gender":"Male","country":"Malaysia"},
{"eid":78,"ename":"Lydon","gender":"Male","country":"Colombia"},
{"eid":79,"ename":"Mortimer","gender":"Male","country":"Uganda"},
{"eid":80,"ename":"Dev","gender":"Male","country":"Indonesia"},
{"eid":81,"ename":"Devina","gender":"Female","country":"Syria"},
{"eid":82,"ename":"Orel","gender":"Female","country":"China"},
{"eid":83,"ename":"Wadsworth","gender":"Genderqueer","country":"China"},
{"eid":84,"ename":"Nelson","gender":"Male","country":"Macedonia"},
{"eid":85,"ename":"Law","gender":"Male","country":"Democratic Republic of the Congo"},
{"eid":86,"ename":"Odelinda","gender":"Female","country":"Dominican Republic"},
{"eid":87,"ename":"Willabella","gender":"Female","country":"China"},
{"eid":88,"ename":"Iain","gender":"Male","country":"Russia"},
{"eid":89,"ename":"Gunar","gender":"Bigender","country":"Comoros"},
{"eid":90,"ename":"Ula","gender":"Female","country":"Indonesia"},
{"eid":91,"ename":"Bab","gender":"Female","country":"Pakistan"},
{"eid":92,"ename":"Calla","gender":"Polygender","country":"China"},
{"eid":93,"ename":"Selina","gender":"Female","country":"Marshall Islands"},
{"eid":94,"ename":"Chloris","gender":"Female","country":"China"},
{"eid":95,"ename":"Kayla","gender":"Female","country":"Sweden"},
{"eid":96,"ename":"Katleen","gender":"Female","country":"Indonesia"},
{"eid":97,"ename":"Whitaker","gender":"Male","country":"South Africa"},
{"eid":98,"ename":"Claudianus","gender":"Male","country":"Argentina"},
{"eid":99,"ename":"Noella","gender":"Female","country":"Colombia"},
{"eid":100,"ename":"Jaquelin","gender":"Female","country":"Russia"}]
male_emp_names=[]
female_emp_names=[]
for emp in employees:
    if emp['gender']=='Male':
        male_emp_names.append(emp['ename']) 

    elif emp['gender'] =='Female':
        female_emp_names.append(emp['ename'])



print(len(male_emp_names))
print(len(female_emp_names))